// flow-typed signature: aee49f7ec091cef4239e200a9fdee8a4
// flow-typed version: <<STUB>>/react-native-cheerio_v^1.0.0-rc.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-cheerio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-cheerio/lib/api/attributes' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/api/css' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/api/forms' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/api/manipulation' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/api/traversing' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/cheerio' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/options' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/parse' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/static' {
  declare module.exports: any;
}

declare module 'react-native-cheerio/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-cheerio/index' {
  declare module.exports: $Exports<'react-native-cheerio'>;
}
declare module 'react-native-cheerio/index.js' {
  declare module.exports: $Exports<'react-native-cheerio'>;
}
declare module 'react-native-cheerio/lib/api/attributes.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/api/attributes'>;
}
declare module 'react-native-cheerio/lib/api/css.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/api/css'>;
}
declare module 'react-native-cheerio/lib/api/forms.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/api/forms'>;
}
declare module 'react-native-cheerio/lib/api/manipulation.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/api/manipulation'>;
}
declare module 'react-native-cheerio/lib/api/traversing.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/api/traversing'>;
}
declare module 'react-native-cheerio/lib/cheerio.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/cheerio'>;
}
declare module 'react-native-cheerio/lib/options.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/options'>;
}
declare module 'react-native-cheerio/lib/parse.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/parse'>;
}
declare module 'react-native-cheerio/lib/static.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/static'>;
}
declare module 'react-native-cheerio/lib/utils.js' {
  declare module.exports: $Exports<'react-native-cheerio/lib/utils'>;
}
